export const GET_MEDICATIONS = 'GET_MEDICATIONS';
export const EDIT_MEDICATION = 'EDIT_MEDICATION';
export const DELETE_MEDICATION = 'DELETE_MEDICATION';
export const ADD_MEDICATION = 'ADD_MEDICATION';
export const GET_ERRORS = 'GET_ERRORS';
export const LOADING = 'LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
